server:
  port: 9905
spring:
  application:
    name: account
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/deliversystem?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka/
  instance:
    instance-id: account-9905
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.summer.entity