server:
  port: 9903
spring:
  application:
    name: client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka/
  instance:
    instance-id: client-9903
    prefer-ip-address: true

